export const cardUsedData = [
    {
        id: 1,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 2,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 3,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 4,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 5,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 6,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 7,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 8,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 9,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 10,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 11,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 12,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 13,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 14,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 15,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 16,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 17,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 18,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 19,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 20,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 21,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 22,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 23,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 24,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 25,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 26,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 27,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 28,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 29,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 30,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 31,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 32,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 33,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 34,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 35,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 36,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 37,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 38,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 39,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 40,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 41,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 42,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 43,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 44,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 45,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 46,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
    {
        id: 47,
        category: '유류비',
        title: 'GS칼텍스',
        price: 30000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 48,
        category: '비품비',
        title: '다이소',
        price: 10000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 49,
        category: '식비',
        title: '맥도날드',
        price: 7000,
        date: '2023-05-01',
        submit: true,
    },
    {
        id: 50,
        category: '식비',
        title: '스타벅스',
        price: 5000,
        date: '2023-05-01',
        submit: false,
    },
]